### ISSUE TITLE
Lag on drawing with touch

### ISSUE THREAD

**Issue by Maleantes** [ivictbor/painterro#42] opened 2018-12-10 15:15 UTC
Hi,

I have a problem to draw with touch on tablet (windows tablet with chrome). When i draw with touchpad, no problem it's fluid, but when i draw with finger or stylet, after few seconds, the coordonates are laggy, and draw lines.

a gif to understand :
https://i.gyazo.com/5c5e2505895a26f3887333c28cde497f.gif

**Comment by ivictbor** [comment] 2018-12-10 15:20
@Maleantes Hi, and thanks for reporting!
Do you try it on fresh page with painterro? A gif show that onmousdown event is fired too rarely, hm. I can't reproduce such behavior on my tablet. What tabled do you have? I need to understand how slow is it.

**Comment by Maleantes** [comment] 2018-12-10 15:36
it's a windows surface 2 and i reproduce too on pc tactile HP Pavilion (icore5/8go ram). But it works very well with touchpad on both of them.

And i realize that no one feature works on IE (v11) ?

**Comment by Maleantes** [comment] 2018-12-10 15:42
draw with finger on firefox works very well too. Just a problem with chrome.

**Comment by Maleantes** [comment] 2018-12-11 10:37
Other question,

I can't write text in IE 11. I had a Promise error, i added es6-promise but now when i valid the text, i don't have any error but that don't work, just the IE console displays "html2canvas $npm_package_version". I added html2canvas.js too but always the same error. I use painterro without npm or other, i just include the js in my page, with jquery 3.3.1, bootstrap, es6-promise/es6-promise-auto and html2canvas.

Can you help me please ?

**Comment by Maleantes** [comment] 2018-12-12 13:52
OK, i have found why chrome lags on drawing. This is because i let touch-action actives. This works very well when i change that to none.

Just need to know for the text bug with IE and i would implement your great plugin very well.

**Comment by ivictbor** [comment] 2018-12-13 08:35
@Maleantes great you found it, I am happy! About but in IE, sorry, I can't even place text box in my IE at all. Unfortunetely have no time now to work on this, but I will remember it for future. Thanks a lot for commenting this issue!

**Comment by ivictbor** [comment] 2019-09-27 08:37
@Maleantes I've added several text fixes in latests versions, please try and create another issue if it is there, this called  "Lag on drawing with touch " so I am closing in as you solved it

**Closed by ivictbor** 2019-09-27 08:37 UTC
