### ISSUE TITLE
Touch Interface

### ISSUE THREAD

**Issue by simontrain** [ivictbor/painterro#3] opened 2017-08-11 17:16 UTC
Hi,
I tried Painterro on an iPad and an Android tablet and it doesn't work. Can't draw, crop or do anything useful. Any plans for adding touch capability?
Thanks, S

**Comment by ivictbor** [comment] 2017-08-11 19:32
Hi, Thank for your interest in painterro.
Yes, unfortunately, full-fledged drawing on touch screens may require different UI approaches than painterro uses now. Currently, it is like desktop old-school mouse painting. 
There are some plans to improve touch (at least implement `ontouch*` events in addition to `onmouse*`, make larger anchors on the cropper, etc) and test how it will be, but I think even in this case it will not be easy to draw something with finger. 
Also, some work will be required to make toolbar responsive for small screens. 
I will respond to this issue when some work will be done on this.

**Comment by simontrain** [comment] 2017-08-11 19:36
Thanks Ivan - great job so far!

Kind regards, Simon

On 11 Aug 2017, at 20:32, Ivan Borshchov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, Thank for your interest in painterro.
Yes, unfortunately, full-fledged drawing on touch screens may require different UI approaches than painterro uses now. Currently, it is like desktop old-school mouse painting.
There are some plans to improve touch (at least implement ontouch* events in addition to onmouse*, make larger anchors on the cropper, etc) and test how it will be, but I think even in this case it will not be easy to draw something with finger.
Also, some work will be required to make toolbar responsive for small screens.
I will respond to this issue when some work will be done on this.

**Comment by ivictbor** [comment] 2017-08-15 20:30
Basic touch interface unlocked. It still has some issues on which I will think later if someone will be interested.
* Currently more than one-finger touches give unexpected behavior in paint tools
* Color picker on touch screen not shown
* Need to add buttons like "Undo", "Clear Area" because there is no keyboard to do this actions with Ctrl+C, Del

**Comment by simontrain** [comment] 2017-08-16 08:41
Great – thanks for the update.

**Comment by Jesfery** [comment] 2017-09-20 01:16
Hi Ivan,

I updated to v0.2.44 yesterday and it seems that since v0.2.43, starting a new "stroke", shape, whatever on touch seems to clear the canvas. I looked at the commits between 0.2.42 and 0.2.43 and couldn't see an obvious culprit. Maybe https://github.com/ivictbor/painterro/commit/f35f1c9898e69ef0b0c5397a63492c27f962dfd2#diff-61e953e7a9fcab8dce82dadac1b664b5?

Just thought you might like to know.

Thanks

Sean

**Comment by ivictbor** [comment] 2017-09-21 16:11
@Jesfery can you please clarify example actions sequence which leads to canvas clearing? I've just tried https://maketips.net/paste on my Android device and it works ok.

**Comment by Jesfery** [comment] 2017-09-25 00:04
Hi Ivan,

Hopefully the attached gif explains what I'm talking about. The same issue happens on my iPhone. I dont have an Android device on hand to try it, but I will tomorrow.

![touch-issue](https://user-images.githubusercontent.com/2281385/30788014-96248bce-a1d8-11e7-87bd-6acba3fdabed.gif)

Thanks

Sean

**Comment by Jesfery** [comment] 2017-09-26 01:56
Hi Ivan,

Just confirming that I was able to replicate the the issue using Chrome on a Samsung Galaxy Tab A (SM-T550) running Android 6.0.1.

Thanks

Sean

**Comment by ivictbor** [comment] 2017-09-29 22:26
@Jesfery thank you very much for helping to reproduce it. You are right - it was caused by this change https://github.com/ivictbor/painterro/commit/f35f1c9898e69ef0b0c5397a63492c27f962dfd2#diff-61e953e7a9fcab8dce82dadac1b664b5, but the root cause was even more important - each draw change was not captured to work log on touch devices because of wrong handling of touch actions. Should work in latest version

**Comment by Jesfery** [comment] 2017-10-03 00:46
@ivictbor Thanks for that. That seems to have resolved the issue.

Sorry to be a pain, but we have noticed an issue with Microsoft Edge on a touch enabled laptop. When you try and draw anything it only leaves a dot at the point where you initially touched the canvas. It doesn't seem to track/trace the rest of the "stroke".

Not sure if thats something you have the capacity to debug or not. Please let me know if theres anything we can do to assist.

Thanks again

Sean

**Comment by ivictbor** [comment] 2017-12-10 12:57
yeah, probably touch actions on in edge on windows touch interfaces are different(or have different fields), then in chrome/safari in Android/iOS. Unfortunately have no such device to test, probably there are some errors in console log (in browser dev tools), they may halp to debug this if any.

**Comment by davesmith9088** [comment] 2018-04-17 14:16
The issue with Microsoft Edge mentioned above is that unfortunately you have to enable the touch API in the settings as it is disabled by default :(

**Comment by davesmith9088** [comment] 2018-04-17 14:25
Some issues still when using Painterro with touch screens (testing on android Chrome) :

* If you zoom in to an image, then try to draw, the canvas moves as you draw
* The responsiveness can be slow sometimes, causing lines to appear jerky - for example a curve may appear as a series of connected straight lines

**Comment by davesmith9088** [comment] 2018-04-17 14:28
Do you have any plans to add more touch screen support?  If not, I may be able to contribute something... let me know! :)

**Comment by ivictbor** [comment] 2018-04-18 10:58
@davesmith9088 in nearest time I am not planning to work on a touch interface, but thanks for the mentioned issues. The contribution will be great I think. Yes, I've also noticed some jerky lines.

**Comment by kishandonepudi** [comment] 2018-07-23 09:38
Is this curve comes in painterro ?

**Comment by ivictbor** [comment] 2018-11-30 23:21
@kishandonepudi what curve?

**Closed** 2019-09-28 22:59 UTC
